const icons = {
    redTearNegativeAIcon: require("@/assets/icons/a-.png"),
    redBagAIcon: require("@/assets/icons/a.png"),
    redBagAPlusIcon: require("@/assets/icons/a+bag.png"),
    redTearNegativeABIcon: require("@/assets/icons/ab-.png"),
    blueBagNegativeABIcon: require("@/assets/icons/ab-bag-blue.png"),
    redBagABIcon: require("@/assets/icons/ab-bag.png"),
    blueBagABPlusIcon: require("@/assets/icons/ab+bag-blue.png"),
    redBagABPlusIcon: require("@/assets/icons/ab+bag-red.png"),
    redBagABPlus1Icon: require("@/assets/icons/ab+bag.png"),
    redBloodBagIcon: require("@/assets/icons/blood-bag.png"),
    redBloodBag1Icon: require("@/assets/icons/blood-bag (1).png"),
    bloodBankIcon: require("@/assets/icons/blood-bank.png"),
    bloodDonationIcon: require("@/assets/icons/blood-donation.png"),
    bloodPressureIcon: require("@/assets/icons/blood-pressure.png"),
    bloodTestPlusIcon: require("@/assets/icons/blood-test-plus.png"),
    bloodTestIcon: require("@/assets/icons/blood-test.png"),
    bloodTypeOIcon: require("@/assets/icons/blood-type-O.png"),
    bloodTypeIcon: require("@/assets/icons/blood-type.png"),
    bloodIcon: require("@/assets/icons/blood.png"),
    boneIcon: require("@/assets/icons/bone.png"),
    brainIcon: require("@/assets/icons/brain.png"),
    colonIcon: require("@/assets/icons/colon.png"),
    corneaIcon: require("@/assets/icons/cornea.png"),
    eyeIcon: require("@/assets/icons/eye.png"),
    fractureIcon: require("@/assets/icons/fracture.png"),
    greenBowHeartIcon: require("@/assets/icons/green-bow-heart.png"),
    greenBowIcon: require("@/assets/icons/green-bow.png"),
    heartDiseaseIcon: require("@/assets/icons/heart-disease.png"),
    heartDonationIcon: require("@/assets/icons/heart-donation.png"),
    heartIcon: require("@/assets/icons/heart.png"),
    hypertensionIcon: require("@/assets/icons/hypertension.png"),
    kidneyIcon: require("@/assets/icons/kidney.png"),
    kidney1Icon: require("@/assets/icons/kidney (1).png"),
    kidney2Icon: require("@/assets/icons/kidney (2).png"),
    kidneysDonationIcon: require("@/assets/icons/kidneys-donation.png"),
    negativeOBagIcon: require("@/assets/icons/o-bag.png"),
    redOPlusIcon: require("@/assets/icons/o+.png"),
    blueBagOPlusIcon: require("@/assets/icons/o+bag-blue.png"),
    redBagOPlusIcon: require("@/assets/icons/o+bag.png"),
    technology1Icon: require("@/assets/icons/technology (1).png"),
    technologyIcon: require("@/assets/icons/technology.png"),
    xRayIcon: require("@/assets/icons/x-ray.png"),
    liverWarningIcon: require("@/assets/icons/liver-warning.png"),
    lungsIcon: require("@/assets/icons/lungs.png"),
    liverIcon: require("@/assets/icons/liver (1).png"),
    kidneyWarningIcon: require("@/assets/icons/kidney-warning.png"),
    orderIcon: require("@/assets/icons/order.png"),
    botIcon: require("@/assets/icons/bot.png"),
    assistantIcon: require("@/assets/icons/assistant.png"),
    reportIcon: require("@/assets/icons/report.png"),
    report1Icon: require("@/assets/icons/report (1).png"),
    seoReportIcon: require("@/assets/icons/seo-report.png"),
    campaignIcon: require("@/assets/icons/campaign.png"),
    campaign1Icon: require("@/assets/icons/campaign (1).png"),
    marketingIcon: require("@/assets/icons/marketing.png"),
    campaign2Icon: require("@/assets/icons/campaign (2).png"),
    checklistIcon: require("@/assets/icons/checklist.png"),
    healthcareIcon: require("@/assets/icons/healthcare.png"),
    donationIcon: require("@/assets/icons/donation.png"),
    recruitment1Icon: require("@/assets/icons/recruitment (1).png"),
    recruitmentIcon: require("@/assets/icons/recruitment.png"),
    findMyFriendIcon: require("@/assets/icons/find-my-friend.png"),
    leucemiaIcon: require("@/assets/icons/leucemia.png"),
    leucemia1Icon: require("@/assets/icons/leucemia (1).png"),
    organDonation1Icon: require("@/assets/icons/organ-donation (1).png"),
    organDonationIcon: require("@/assets/icons/organ-donation.png"),
    kidneyDonorIcon: require("@/assets/icons/kidney-donor.png"),
}

export default icons;